### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by v-thepet**

### CODE REVIEW

**Comment by v-thepet** [comment]
@twooley - Please review the changes. If approved, @rloutlaw can merge. (Note that the Data Lake Blog name has not changed.) Thanks.

**Comment by twooley** [comment]
@v-thepet I think the "Azure Data Lake Storage Gen1 homepage" link should remain "Azure Data Lake homepage" since it look like it applies to both Data Lake Store (now Gen1 of course) and Data Lake Analytics (which both fall under the Azure Data Lake umbrella).

**Comment by v-thepet** [comment]
@twooley - This fix is made, thanks.

**Comment by twooley** [comment]
@v-thepet Looks good. @rloutlaw Robert, can you please merge? Thanks!

**Pull request merged**
